import { StyleSheet } from 'react-native';
import { ThemeColors } from '../theme/colors';

export const RegistroVisitaScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: ThemeColors.background,
    },
    headerCard: {
        backgroundColor: '#14532D',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        width: '100%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 4,
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#86EFAC',
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        marginBottom: 4,
        fontWeight: '700',
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 12,
    },
    badgeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 20,
        alignSelf: 'flex-start',
    },
    badgeDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#4ADE80',
        marginRight: 6,
    },
    badgeText: {
        color: '#E2E8F0',
        fontSize: 12,
        fontWeight: '500',
    },
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 18,
        marginBottom: 16,
        width: '100%',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 14,
    },
    sectionIconBox: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: '#DCFCE7',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1E293B',
    },
    input: {
        width: '100%',
        height: 50,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        borderRadius: 10,
        paddingHorizontal: 14,
        fontSize: 15,
        backgroundColor: '#F8FAFC',
        color: '#052E16',
        marginBottom: 12,
    },
    textArea: {
        height: 90,
        paddingTop: 12,
        textAlignVertical: 'top',
    },
    imagePreviewContainer: {
        width: '100%',
        height: 210,
        borderRadius: 12,
        backgroundColor: '#F0FDF4',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: '#86EFAC',
        borderStyle: 'dashed',
        overflow: 'hidden',
        marginBottom: 12,
    },
    imagePreview: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    emptyText: {
        color: '#64748B',
        fontSize: 14,
        fontWeight: '500',
    },
    permissionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },
    permissionLabel: {
        fontSize: 14,
        color: '#475569',
        fontWeight: '500',
    },
    statusGranted: {
        color: '#16A34A',
        fontWeight: '600',
        fontSize: 14,
    },
    statusDenied: {
        color: '#DC2626',
        fontWeight: '600',
        fontSize: 14,
    },
    statusPending: {
        color: '#D97706',
        fontWeight: '600',
        fontSize: 14,
    },
    pressableMargin: {
        marginTop: 4,
    },
    telemetryBox: {
        backgroundColor: '#052E16',
        borderRadius: 12,
        padding: 14,
        marginBottom: 16,
    },
    telemetryTitle: {
        color: '#94A3B8',
        fontSize: 11,
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 6,
        fontWeight: '700',
    },
    telemetryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    telemetryText: {
        color: '#F8FAFC',
        fontFamily: 'monospace',
        fontSize: 13,
    },
    telemetryBarTrack: {
        height: 6,
        borderRadius: 3,
        backgroundColor: '#14532D',
        marginTop: 10,
        overflow: 'hidden',
    },
    telemetryBarFill: {
        height: 6,
        borderRadius: 3,
    },
    photoTagOverlay: {
        position: 'absolute',
        left: 8,
        bottom: 8,
        backgroundColor: 'rgba(5, 46, 16, 0.78)',
        paddingHorizontal: 8,
        paddingVertical: 5,
        borderRadius: 6,
    },
    photoTagText: {
        color: '#F8FAFC',
        fontFamily: 'monospace',
        fontSize: 10,
    },
    // Card de georreferenciação
    gpsCoords: {
        fontSize: 13,
        color: '#334155',
        fontFamily: 'monospace',
    },
    gpsMetaLinha: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    gpsPonto: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 6,
    },
    gpsMetaTexto: {
        fontSize: 12,
        color: '#64748B',
    },
    avisoBanner: {
        marginBottom: 12,
        padding: 10,
        borderRadius: 8,
        backgroundColor: '#FEF3C7',
        borderLeftWidth: 4,
        borderLeftColor: ThemeColors.warning,
    },
    avisoTexto: {
        fontSize: 13,
        color: '#92400E',
    },
    // Botões da evidência fotográfica
    fotoBotoesLinha: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    fotoBotaoItem: {
        flexGrow: 1,
        minWidth: 140,
    },
    fotoVaziaBox: {
        alignItems: 'center',
    },
    // Laudo assinado
    sucessoCard: {
        backgroundColor: '#F0FDF4',
        borderColor: '#BBF7D0',
    },
    sucessoCabecalho: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    sucessoTitulo: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#166534',
    },
    sucessoDados: {
        fontSize: 13,
        color: '#374151',
        fontFamily: 'monospace',
    },
});